/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package online.banking;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author mcman
 */
public class AddAccount extends javax.swing.JDialog {

    /**
     * Creates new form AddAccount
     */
    Bank bank;

    public AddAccount(java.awt.Frame parent, boolean modal, Bank bank) {
        super(parent, modal);
        initComponents();
        this.bank = bank;
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PasswordField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        SSNField = new javax.swing.JTextField();
        AddAccountButton = new javax.swing.JButton();
        UserNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SavingsField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CheckingField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        BranchField = new javax.swing.JTextField();
        RemoveAccountButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Social Security Number");

        AddAccountButton.setText("Create Account");
        AddAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAccountButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Enter UserName");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Enter Password");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Savings Balance");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Checking Balance");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Branch");

        RemoveAccountButton.setText("Delete Account");
        RemoveAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveAccountButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(BranchField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(SavingsField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(CheckingField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(PasswordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SSNField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(UserNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RemoveAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BranchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SavingsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CheckingField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SSNField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddAccountButton)
                    .addComponent(RemoveAccountButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CancelButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAccountButtonActionPerformed
        String username = "";
        String password = "";
        String ConfirmPassword = "";
        String ssn = "";
        double savingBalance = 0;
        double checkingBalance = 0;
        String BranchName = "";
        StringBuilder warnings = new StringBuilder();
        if (UserNameField.getText().isEmpty()) {
            warnings.append("Username must not be empty.\n");
        } else {
            username = UserNameField.getText();
        }
        //Verify last name field
        if (PasswordField.getText().isEmpty()) {
            warnings.append("Last name must not be empty.\n");
        } else {
            password = PasswordField.getText();
        }
        if (!SSNField.getText().matches("\\d{3}-?\\d{2}-?\\d{4}")) {
            warnings.append("SSN must be 9 digits, dashes are acceptable.\n");
        } else {
            ssn = SSNField.getText().replace("-", "");
        }
        if (CheckingField.getText().isEmpty()) {
            warnings.append("Checking must not be empty.\n");
        } else {
            checkingBalance = Double.parseDouble(CheckingField.getText());
        }
        if (SavingsField.getText().isEmpty()) {
            warnings.append("Savings must not be empty.\n");
        } else {
            savingBalance = Double.parseDouble(SavingsField.getText());
        }
        if (BranchField.getText().isEmpty()) {
            warnings.append("Branch must not be empty.\n");
        } else {
            BranchName = BranchField.getText();
        }
        if (warnings.length() > 0) {
            JOptionPane.showMessageDialog(this, warnings.toString(), "Input Warnings", JOptionPane.WARNING_MESSAGE);
        } else {
            ArrayList<User> userList = new ArrayList<>();
            int x = 0;
            for (Branch branch : bank.getBranches()) {
                if (BranchName.equals(branch.getName())) {
                    branch.addUser(username, ssn, password, checkingBalance, savingBalance);
                    x = 1;
                }
            }
            if (x != 1) {
                bank.addBranch(BranchName, userList).addUser(username, ssn, password, checkingBalance, savingBalance);
            }
            MainMenu Menu = new MainMenu(bank);
            Menu.setLocationRelativeTo(this);
            this.dispose();
            Menu.setVisible(true);
        }
    }//GEN-LAST:event_AddAccountButtonActionPerformed

    private void RemoveAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveAccountButtonActionPerformed

        String username = "";
        String password = "";
        String ssn = "";
        String BranchName = "";
        StringBuilder warnings = new StringBuilder();
        StringBuilder Accountwarnings = new StringBuilder();
        if (UserNameField.getText().isEmpty()) {
            warnings.append("Username must not be empty.\n");
        } else {
            username = UserNameField.getText();
        }
        //Verify last name field
        if (PasswordField.getText().isEmpty()) {
            warnings.append("Last name must not be empty.\n");
        } else {
            password = PasswordField.getText();
        }
        if (!SSNField.getText().matches("\\d{3}-?\\d{2}-?\\d{4}")) {
            warnings.append("SSN must be 9 digits, dashes are acceptable.\n");
        } else {
            ssn = SSNField.getText().replace("-", "");
        }
        if (BranchField.getText().isEmpty()) {
            warnings.append("Branch must not be empty.\n");
        } else {
            BranchName = BranchField.getText();
        }
        if (warnings.length() > 0) {
            JOptionPane.showMessageDialog(this, warnings.toString(), "Input Warnings", JOptionPane.WARNING_MESSAGE);
        } else {
            int userPlace = -1;
            int x = -1;
            for (Branch branch : bank.getBranches()) {
                x++;

                if (BranchName.equals(branch.getName())) {
                    userPlace = branch.compare(username, ssn, password);
                    break;
                }
            }
            
            if (userPlace != -1 && x != bank.getBranches().size() - 1) {
                bank.getBranches().get(x).removeUser(bank.getBranches().get(x).getUsers().get(userPlace));
                if (bank.getBranches().get(x).getUsers().size() < 1) {
                    bank.removeBranch(bank.getBranches().get(x));
                }
                MainMenu Menu = new MainMenu(bank);
                Menu.setLocationRelativeTo(this);
                this.dispose();
                Menu.setVisible(true);
            } else if (userPlace == -1 && x != bank.getBranches().size() - 1) {
                Accountwarnings.append("Enter Valid User");
                JOptionPane.showMessageDialog(this, Accountwarnings.toString(), "Input Warnings", JOptionPane.WARNING_MESSAGE);
            } else if (userPlace != -1 && x == bank.getBranches().size() - 1) {
                Accountwarnings.append("Enter Valid Branch\n");
                JOptionPane.showMessageDialog(this, Accountwarnings.toString(), "Input Warnings", JOptionPane.WARNING_MESSAGE);
            }else{
                Accountwarnings.append("Enter Valid Branch\n");
                Accountwarnings.append("Enter Valid User");
                JOptionPane.showMessageDialog(this, Accountwarnings.toString(), "Input Warnings", JOptionPane.WARNING_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_RemoveAccountButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        MainMenu Menu = new MainMenu(bank);
        Menu.setLocationRelativeTo(this);
        this.dispose();
        Menu.setVisible(true);
    }//GEN-LAST:event_CancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAccountButton;
    private javax.swing.JTextField BranchField;
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField CheckingField;
    private javax.swing.JTextField PasswordField;
    private javax.swing.JButton RemoveAccountButton;
    private javax.swing.JTextField SSNField;
    private javax.swing.JTextField SavingsField;
    private javax.swing.JTextField UserNameField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
