/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package online.banking;

import java.util.ArrayList;
import java.util.List;
import javax.swing.*;

/**
 *
 * @author mcman
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    String AccountType;


    Bank bank;
    int currentUser;

    public MainMenu(Bank bank) {

        initComponents();
        setLocationRelativeTo(null);
        //Disable sign in buttons
        this.bank = bank;

        
        UserNameField.setEnabled(false);
        ConfirmPasswordField.setEnabled(false);
        PasswordField.setEnabled(false);
        SSNField.setEnabled(false);
        SignInButton.setEnabled(false);
        
        for(Branch branch : bank.getBranches())  
            BranchSelectionBox.addItem(branch.getName());
        //Disable Account buttons
        AccountSelectionBox.setEnabled(false);
        AccountBalanceField.setEnabled(false);
        AccountBalanceField.setEditable(false);
        AmountField.setEnabled(false);
        WithdrawalButton.setEnabled(false);
        DepositButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        BranchSelectionBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UserNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ConfirmPasswordField = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        SSNField = new javax.swing.JTextField();
        AccountSelectionBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        AmountField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        AccountBalanceField = new javax.swing.JTextField();
        WithdrawalButton = new javax.swing.JButton();
        DepositButton = new javax.swing.JButton();
        SignInButton = new javax.swing.JButton();
        AddAccountButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bank Application");

        BranchSelectionBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        BranchSelectionBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                BranchSelectionBoxItemStateChanged(evt);
            }
        });
        BranchSelectionBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BranchSelectionBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome To Banking Application");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Select Branch");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Enter UserName");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Enter Password");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Confirm Password");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Social Security Number");

        AccountSelectionBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Checkings", "Savings" }));
        AccountSelectionBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountSelectionBoxActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Select Account");

        AmountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmountFieldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Enter Amount");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Account Balance");

        AccountBalanceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountBalanceFieldActionPerformed(evt);
            }
        });

        WithdrawalButton.setText("Withdrawal");
        WithdrawalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawalButtonActionPerformed(evt);
            }
        });

        DepositButton.setText("Deposit");
        DepositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositButtonActionPerformed(evt);
            }
        });

        SignInButton.setText("Sign In");
        SignInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInButtonActionPerformed(evt);
            }
        });

        AddAccountButton.setText("Add/Delete Account");
        AddAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAccountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(BranchSelectionBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(UserNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(PasswordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AccountSelectionBox, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(SSNField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SignInButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AddAccountButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(ConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(AccountBalanceField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(AmountField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(WithdrawalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(DepositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(12, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BranchSelectionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccountSelectionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SSNField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SignInButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddAccountButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AccountBalanceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AmountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(WithdrawalButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DepositButton)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AccountSelectionBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountSelectionBoxActionPerformed
        String accountType = (AccountSelectionBox.getSelectedItem()).toString();
        AccountType = accountType;
        for (Branch branch : bank.getBranches()) {
            if (BranchSelectionBox.getSelectedItem().equals(branch.getName())) {
                if (AccountType.equals("Checkings")) {
                    AccountBalanceField.setText(Double.toString(branch.getUsers().get(currentUser).checking.getBalance()));
                    WithdrawalButton.setEnabled(true);
                    DepositButton.setEnabled(true);
                    AmountField.setEnabled(true);
                }
                if (AccountType.equals("Savings")) {
                    AccountBalanceField.setText(Double.toString(branch.getUsers().get(currentUser).saving.getBalance()));
                    WithdrawalButton.setEnabled(true);
                    DepositButton.setEnabled(true);
                    AmountField.setEnabled(true);
                }
                if (AccountType.equals("Select")) {
                    AccountBalanceField.setText(Double.toString(0));
                    WithdrawalButton.setEnabled(false);
                    DepositButton.setEnabled(false);
                    AmountField.setEnabled(false);
                    AmountField.setText("");
                }
            }
        }

    }//GEN-LAST:event_AccountSelectionBoxActionPerformed

    private void SignInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInButtonActionPerformed
        String username = "";
        String password = "";
        String ConfirmPassword = "";
        String ssn = "";
        StringBuilder warnings = new StringBuilder();
        if (UserNameField.getText().isEmpty()) {
            warnings.append("Username must not be empty.\n");
        } else {
            username = UserNameField.getText();
        }
        //Verify last name field
        if (PasswordField.getText().isEmpty()) {
            warnings.append("Last name must not be empty.\n");
        } else {
            password = PasswordField.getText();
        }
        if (!SSNField.getText().matches("\\d{3}-?\\d{2}-?\\d{4}")) {
            warnings.append("SSN must be 9 digits, dashes are acceptable.\n");
        } else {
            ssn = SSNField.getText().replace("-", "");
        }
        //Verify initial deposit
        if (ConfirmPasswordField.getText().isEmpty() || !ConfirmPasswordField.getText().equals(PasswordField.getText())) {
            warnings.append("Passwords Must Match");
        } else {
            ConfirmPassword = ConfirmPasswordField.getText();
        }
        if (warnings.length() > 0) {
            JOptionPane.showMessageDialog(this, warnings.toString(), "Input Warnings", JOptionPane.WARNING_MESSAGE);
        } else {
            //Toronto.getUsers().get(currentUser);
            boolean signedIn = false;
            for (Branch branch : bank.getBranches()) {
                if (BranchSelectionBox.getSelectedItem().equals(branch.getName())) {
                    currentUser = branch.compare(username, ssn, password);
                    signedIn = currentUser != -1;
                }
                if (signedIn) {
                    AccountSelectionBox.setSelectedIndex(0);
                    AccountSelectionBox.setEnabled(true);
                    AccountBalanceField.setText("");
                    AccountBalanceField.setEnabled(true);
                    AmountField.setText("");
                    AmountField.setEnabled(true);
                } else {
                    AccountSelectionBox.setSelectedIndex(0);
                    AccountSelectionBox.setEnabled(false);
                    AccountBalanceField.setText("");
                    AccountBalanceField.setEnabled(false);
                    AmountField.setText("");
                    AmountField.setEnabled(false);
                }
            }
        }

    }//GEN-LAST:event_SignInButtonActionPerformed

    private void BranchSelectionBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BranchSelectionBoxActionPerformed

    }//GEN-LAST:event_BranchSelectionBoxActionPerformed

    private void BranchSelectionBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_BranchSelectionBoxItemStateChanged

        if (!BranchSelectionBox.getSelectedItem().equals("Select")) {
            UserNameField.setEnabled(true);
            UserNameField.setText("");
            ConfirmPasswordField.setEnabled(true);
            ConfirmPasswordField.setText("");
            PasswordField.setEnabled(true);
            PasswordField.setText("");
            SSNField.setEnabled(true);
            SSNField.setText("");
            SignInButton.setEnabled(true);
            AccountSelectionBox.setEnabled(false);
            AccountBalanceField.setText("");
            AccountBalanceField.setEnabled(false);
            AmountField.setText("");
            AmountField.setEnabled(false);
            AmountField.setEnabled(false);
            WithdrawalButton.setEnabled(false);
            DepositButton.setEnabled(false);
        } else {
            UserNameField.setEnabled(false);
            ConfirmPasswordField.setEnabled(false);
            PasswordField.setEnabled(false);
            SSNField.setEnabled(false);
            SignInButton.setEnabled(false);
            AccountSelectionBox.setEnabled(false);
            AccountBalanceField.setText("");
            AccountBalanceField.setEnabled(false);
            AmountField.setText("");
            AmountField.setEnabled(false);
            AmountField.setEnabled(false);
            WithdrawalButton.setEnabled(false);
            DepositButton.setEnabled(false);
        }
    }//GEN-LAST:event_BranchSelectionBoxItemStateChanged

    private void AccountBalanceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountBalanceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccountBalanceFieldActionPerformed

    private void WithdrawalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawalButtonActionPerformed
        double amount = Double.parseDouble(AmountField.getText());
        for (Branch branch : bank.getBranches()) {
            if (BranchSelectionBox.getSelectedItem().equals(branch.getName())) {
                if (AccountType.equals("Checkings")) {
                    branch.getUsers().get(currentUser).checking.withdrawal(amount);
                    AccountBalanceField.setText(Double.toString(branch.getUsers().get(currentUser).checking.getBalance()));
                }
                if (AccountType.equals("Savings")) {
                    branch.getUsers().get(currentUser).saving.withdrawal(amount);
                    AccountBalanceField.setText(Double.toString(branch.getUsers().get(currentUser).saving.getBalance()));
                }
            }
        }
    }//GEN-LAST:event_WithdrawalButtonActionPerformed

    private void AmountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AmountFieldActionPerformed

    private void DepositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositButtonActionPerformed
        double amount = Double.parseDouble(AmountField.getText());
        for (Branch branch : bank.getBranches()) {
            if (BranchSelectionBox.getSelectedItem().equals(branch.getName())) {
                if (AccountType.equals("Checkings")) {
                    branch.getUsers().get(currentUser).checking.deposit(amount);
                    AccountBalanceField.setText(Double.toString(branch.getUsers().get(currentUser).checking.getBalance()));
                }
                if (AccountType.equals("Savings")) {
                    branch.getUsers().get(currentUser).saving.deposit(amount);
                    AccountBalanceField.setText(Double.toString(branch.getUsers().get(currentUser).saving.getBalance()));
                }
            }
        }
    }//GEN-LAST:event_DepositButtonActionPerformed

    private void AddAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAccountButtonActionPerformed
        AddAccount addAccount = new AddAccount(this,true,bank);
        this.dispose();
        addAccount.setVisible(true);
        
    }//GEN-LAST:event_AddAccountButtonActionPerformed
    public void setBank(Bank bank){
        this.bank=bank;
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccountBalanceField;
    private javax.swing.JComboBox<String> AccountSelectionBox;
    private javax.swing.JButton AddAccountButton;
    private javax.swing.JTextField AmountField;
    private javax.swing.JComboBox<String> BranchSelectionBox;
    private javax.swing.JPasswordField ConfirmPasswordField;
    private javax.swing.JButton DepositButton;
    private javax.swing.JTextField PasswordField;
    private javax.swing.JTextField SSNField;
    private javax.swing.JButton SignInButton;
    private javax.swing.JTextField UserNameField;
    private javax.swing.JButton WithdrawalButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
